import type {
  InboundReceiptDetail,
  InboundReceiptQueueResponse,
} from "@fosholhaat/types";
import { InboundReceiptStatus } from "@fosholhaat/types";

export const HUB_INBOUND_QUEUE: InboundReceiptQueueResponse = {
  summary: {
    PENDING: 2,
    RECEIVED: 1,
    DISCREPANCY: 1,
    total: 4,
  },
  activeTab: InboundReceiptStatus.PENDING,
  featuredReceiptId: "IR-6201",
  receipts: [
    {
      id: "IR-6201",
      supplierName: "Kazi Traders",
      commodity: "Potato",
      expectedQuantity: 820,
      unit: "bags",
      status: InboundReceiptStatus.PENDING,
      arrivalDate: "21 Apr 2026",
      arrivalWindowLabel: "08:00-09:30",
      laneLabel: "North intake bay",
      note: "Gate slip ready, weight still waiting for confirmation.",
    },
    {
      id: "IR-6202",
      supplierName: "Farid & Sons",
      commodity: "Onion",
      expectedQuantity: 540,
      unit: "bags",
      status: InboundReceiptStatus.RECEIVED,
      arrivalDate: "21 Apr 2026",
      arrivalWindowLabel: "09:45-10:30",
      laneLabel: "Dock 2",
      note: "Closed against the supplier note after cross-check.",
    },
    {
      id: "IR-6203",
      supplierName: "Sajal Veg Supply",
      commodity: "Vegetables",
      expectedQuantity: 310,
      unit: "crates",
      status: InboundReceiptStatus.DISCREPANCY,
      arrivalDate: "21 Apr 2026",
      arrivalWindowLabel: "10:30-11:15",
      laneLabel: "Cold bay",
      note: "Short count flagged before sorting release.",
    },
    {
      id: "IR-6204",
      supplierName: "Milon Agro",
      commodity: "Potato",
      expectedQuantity: 680,
      unit: "bags",
      status: InboundReceiptStatus.PENDING,
      arrivalDate: "21 Apr 2026",
      arrivalWindowLabel: "11:30-12:15",
      laneLabel: "South intake bay",
      note: "Batch note attached, receiver sign-off pending.",
    },
  ],
};

export const HUB_INBOUND_DETAILS: Record<string, InboundReceiptDetail> = {
  "IR-6201": {
    ...HUB_INBOUND_QUEUE.receipts[0],
    receivedAt: null,
    expectedGradeLabel: "Grade A",
    actualGradeLabel: null,
    receiverName: null,
    discrepancy: null,
    nextStepLabel: "Wait for weight confirmation, then release to sorting.",
  },
  "IR-6202": {
    ...HUB_INBOUND_QUEUE.receipts[1],
    receivedAt: "21 Apr 2026, 10:18",
    expectedGradeLabel: "Grade A",
    actualGradeLabel: "Grade A",
    receiverName: "Aminul Islam",
    discrepancy: null,
    nextStepLabel: "Receipt already closed; no further action needed.",
  },
  "IR-6203": {
    ...HUB_INBOUND_QUEUE.receipts[2],
    receivedAt: null,
    expectedGradeLabel: "Grade B",
    actualGradeLabel: "Grade C",
    receiverName: "Rashed Khan",
    discrepancy: {
      reportedAt: "21 Apr 2026, 11:04",
      actualQuantity: 286,
      notes: "Fourteen crates short against the gate tally.",
    },
    nextStepLabel: "Hold release until the discrepancy note is reviewed.",
  },
  "IR-6204": {
    ...HUB_INBOUND_QUEUE.receipts[3],
    receivedAt: null,
    expectedGradeLabel: "Grade A",
    actualGradeLabel: null,
    receiverName: null,
    discrepancy: null,
    nextStepLabel: "Confirm gate count and assign the receiver.",
  },
};
