import { BuyerOrderDetail, Locale } from '@fosholhaat/types';

export const getOrderCopy = (locale: Locale) => {
  return locale === 'bn'
    ? {
        title: 'আমার অর্ডার',
        subtitle: 'আপনার সব অর্ডারের তথ্য এখানে দেখুন',
        ongoing: 'চলমান',
        completed: 'সম্পন্ন',
        all: 'সব',
        track: 'ট্র্যাক করুন',
        viewDetails: 'বিস্তারিত',
        orderId: 'অর্ডার আইডি',
        total: 'মোট',
        date: 'তারিখ',
        status: 'অবস্থা',
        processing: 'প্রসেসিং',
        inTransit: 'পথে আছে',
        shipped: 'পাঠানো হয়েছে',
        delivered: 'ডেলিভারি হয়েছে',
        items: 'পণ্যসমূহ',
        deliveryAddress: 'ডেলিভারি ঠিকানা',
        paymentMethod: 'পেমেন্ট পদ্ধতি',
        pricing: 'মূল্যের বিবরণ',
        subtotal: 'উপ-মোট',
        deliveryFee: 'ডেলিভারি চার্জ',
        bulkSavings: 'বাল্ক সাশ্রয়',
        totalAmount: 'মোট পরিমাণ',
        tracking: 'অর্ডার ট্র্যাকিং',
        estArrival: 'সম্ভাব্য পৌঁছানোর সময়',
        quantity: 'পরিমাণ',
        verified: 'নিশ্চিত',
        needHelp: 'সাহায্য লাগলে',
        currentlyActive: 'এখন চলছে',
        orderConfirmed: 'অর্ডার নিশ্চিত',
        packedAtHub: 'হাবে প্যাক',
        logisticsInfo: 'ডেলিভারি তথ্য',
        truckId: 'ট্রাক আইডি',
        fleet: 'ফ্লিট',
        callDriver: 'ড্রাইভার',
        message: 'মেসেজ',
        orderSnapshot: 'অর্ডার সারাংশ',
        contact: 'যোগাযোগ',
        viewOrderDetails: 'অর্ডার দেখুন',
        notFoundTitle: 'অর্ডার পাওয়া যায়নি',
        notFoundBody: 'এই অর্ডারটি এখন নেই বা আইডি ভুল।',
        backToOrders: 'অর্ডারে ফিরুন',
      }
    : {
        title: 'My Orders',
        subtitle: 'View and track all your orders',
        ongoing: 'Ongoing',
        completed: 'Completed',
        all: 'All',
        track: 'Track Order',
        viewDetails: 'View Details',
        orderId: 'Order ID',
        total: 'Total',
        date: 'Date',
        status: 'Status',
        processing: 'Processing',
        inTransit: 'In Transit',
        shipped: 'Shipped',
        delivered: 'Delivered',
        items: 'Items',
        deliveryAddress: 'Delivery Address',
        paymentMethod: 'Payment Method',
        pricing: 'Pricing Breakdown',
        subtotal: 'Subtotal',
        deliveryFee: 'Delivery Fee',
        bulkSavings: 'Bulk Savings',
        totalAmount: 'Total Amount',
        tracking: 'Order Tracking',
        estArrival: 'Est. Arrival',
        quantity: 'Quantity',
        verified: 'Verified',
        needHelp: 'Need help',
        currentlyActive: 'Live now',
        orderConfirmed: 'Order confirmed',
        packedAtHub: 'Packed at hub',
        logisticsInfo: 'Delivery info',
        truckId: 'Truck ID',
        fleet: 'Fleet',
        callDriver: 'Driver',
        message: 'Message',
        orderSnapshot: 'Order snapshot',
        contact: 'Contact',
        viewOrderDetails: 'View order',
        notFoundTitle: 'Order not found',
        notFoundBody: 'This order is missing or the ID is wrong.',
        backToOrders: 'Back to orders',
      };
};

export const getOrderById = (orderId: string) => MOCK_ORDERS.find((order) => order.id === orderId) ?? null;

export const getOrderStatusLabel = (locale: Locale, status: BuyerOrderDetail['status']) => {
  const copy = getOrderCopy(locale);
  if (status === 'IN_TRANSIT') return copy.inTransit;
  if (status === 'PROCESSING') return copy.processing;
  if (status === 'SHIPPED') return copy.shipped;
  return copy.delivered;
};

export const MOCK_ORDERS: BuyerOrderDetail[] = [
  {
    id: 'FH-8492',
    status: 'IN_TRANSIT',
    title: '60 Bags: Red Onions, Premium Rice',
    total: '৳45,200',
    estDelivery: 'Oct 26',
    imageUrl: 'https://images.unsplash.com/photo-1601648764658-cf37e8c89b70?auto=format&fit=crop&q=80&w=200',
    dateGroup: 'TODAY, 24 OCT',
    items: [
      { name: 'Red Onions', quantity: '40 Bags', price: '৳28,000' },
      { name: 'Premium Rice', quantity: '20 Bags', price: '৳17,200' },
    ],
    shippingAddress: 'Plot 12, Sector 3, Uttara, Dhaka',
    paymentMethod: 'Cash on Delivery',
    subtotal: '৳45,000',
    deliveryFee: '৳200',
  },
  {
    id: 'FH-8510',
    status: 'PROCESSING',
    title: '120 Sacks: Green Lentils (Grade A)',
    total: '৳1,12,000',
    estDelivery: 'Oct 28',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=200',
    dateGroup: 'TODAY, 24 OCT',
    items: [
      { name: 'Green Lentils (Grade A)', quantity: '120 Sacks', price: '৳1,11,500' },
    ],
    shippingAddress: 'Plot 12, Sector 3, Uttara, Dhaka',
    paymentMethod: 'Bank Transfer',
    subtotal: '৳1,11,500',
    deliveryFee: '৳500',
  },
  {
    id: 'FH-8388',
    status: 'SHIPPED',
    title: '45 Crates: Fresh Ginger, Garlic',
    total: '৳32,800',
    estDelivery: 'Oct 25',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=200',
    dateGroup: 'YESTERDAY, 23 OCT',
    items: [
      { name: 'Fresh Ginger', quantity: '25 Crates', price: '৳18,000' },
      { name: 'Garlic', quantity: '20 Crates', price: '৳14,500' },
    ],
    shippingAddress: 'Plot 12, Sector 3, Uttara, Dhaka',
    paymentMethod: 'Cash on Delivery',
    subtotal: '৳32,500',
    deliveryFee: '৳300',
  },
];
