import type { Locale } from '@fosholhaat/types';

export const getOrderCopy = (locale: Locale) => {
  return locale === 'bn'
    ? {
        listTitle: 'আমার অর্ডার',
        listSubtitle: 'আপনার সব অর্ডারের তথ্য এখানে দেখুন',
        ongoing: 'চলমান',
        completed: 'সম্পন্ন',
        all: 'সব',
        total: 'মোট',
        estDelivery: 'সম্ভাব্য ডেলিভারি',
        track: 'ট্র্যাকিং',
        viewDetails: 'বিস্তারিত দেখুন',
        statusSummary: 'অর্ডারের অবস্থা',
        estimated: 'সম্ভাব্য তারিখ',
        orderItems: 'অর্ডারের পণ্যসমূহ',
        quantity: 'পরিমাণ',
        pricingBreakdown: 'মূল্যের বিবরণ',
        subtotal: 'উপ-মোট',
        deliveryFee: 'ডেলিভারি চার্জ',
        bulkSavings: 'বাল্ক সাশ্রয়',
        totalAmount: 'মোট টাকা',
        fulfillment: 'ডেলিভারি সেন্টার',
        payment: 'পেমেন্ট পদ্ধতি',
        status: 'অবস্থা',
        verified: 'যাচাইকৃত',
        needHelp: 'সাহায্য প্রয়োজন?',
        processing: 'প্রসেসিং হচ্ছে',
        inTransit: 'পথে আছে',
        shipped: 'পাঠানো হয়েছে',
        delivered: 'ডেলিভারি হয়েছে',
        orderConfirmed: 'অর্ডার নিশ্চিত করা হয়েছে',
        packedAtHub: 'হাবে প্যাকিং হয়েছে',
        currentlyActive: 'বর্তমানে সক্রিয়',
        lastPing: 'শেষ অবস্থান',
      }
    : {
        listTitle: 'My Orders',
        listSubtitle: 'View and track all your orders',
        ongoing: 'Ongoing',
        completed: 'Completed',
        all: 'All',
        total: 'Total',
        estDelivery: 'Est. Delivery',
        track: 'Track',
        viewDetails: 'View Details',
        statusSummary: 'Order Status',
        estimated: 'Estimated',
        orderItems: 'Order Items',
        quantity: 'Quantity',
        pricingBreakdown: 'Pricing Breakdown',
        subtotal: 'Subtotal',
        deliveryFee: 'Delivery Fee',
        bulkSavings: 'Bulk Savings',
        totalAmount: 'Total Amount',
        fulfillment: 'Fulfillment Center',
        payment: 'Payment Info',
        status: 'Status',
        verified: 'Verified',
        needHelp: 'Need Help?',
        processing: 'Processing',
        inTransit: 'In Transit',
        shipped: 'Shipped',
        delivered: 'Delivered',
        orderConfirmed: 'Order Confirmed',
        packedAtHub: 'Packed at Hub',
        currentlyActive: 'Currently Active',
        lastPing: 'Last Location',
      };
};
